#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Phoneword.Resource", IsApplication=true)]

namespace Phoneword
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.font = global::Phoneword.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::Phoneword.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::Phoneword.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::Phoneword.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::Phoneword.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::Phoneword.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::Phoneword.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::Phoneword.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::Phoneword.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Boolean.abc_action_bar_embed_tabs = global::Phoneword.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::Phoneword.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::Phoneword.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::Phoneword.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::Phoneword.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::Phoneword.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::Phoneword.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::Phoneword.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::Phoneword.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::Phoneword.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::Phoneword.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::Phoneword.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::Phoneword.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::Phoneword.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::Phoneword.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::Phoneword.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::Phoneword.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::Phoneword.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::Phoneword.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::Phoneword.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::Phoneword.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::Phoneword.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::Phoneword.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::Phoneword.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::Phoneword.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::Phoneword.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::Phoneword.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::Phoneword.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::Phoneword.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::Phoneword.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::Phoneword.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::Phoneword.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::Phoneword.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::Phoneword.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::Phoneword.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::Phoneword.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::Phoneword.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::Phoneword.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::Phoneword.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::Phoneword.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::Phoneword.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::Phoneword.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.async = global::Phoneword.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::Phoneword.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::Phoneword.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::Phoneword.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::Phoneword.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::Phoneword.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::Phoneword.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::Phoneword.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::Phoneword.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::Phoneword.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::Phoneword.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::Phoneword.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::Phoneword.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::Phoneword.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::Phoneword.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::Phoneword.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.text = global::Phoneword.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::Phoneword.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::Phoneword.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::Phoneword.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::Phoneword.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::Phoneword.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::Phoneword.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::Phoneword.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::Phoneword.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::Phoneword.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::Phoneword.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::Phoneword.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::Phoneword.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::Phoneword.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Phoneword.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::Phoneword.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::Phoneword.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::Phoneword.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::Phoneword.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::Phoneword.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::Phoneword.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::Phoneword.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::Phoneword.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Phoneword.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Phoneword.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::Phoneword.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::Phoneword.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::Phoneword.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::Phoneword.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::Phoneword.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::Phoneword.Resource.Styleable.FontFamilyFont_fontWeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs = 2131099648;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int compat_button_inset_horizontal_material = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int compat_button_inset_vertical_material = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_padding_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_padding_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_control_corner_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_action_icon_size = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int notification_action_text_size = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int notification_big_circle_margin = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int notification_content_margin_start = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int notification_large_icon_height = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_large_icon_width = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int notification_main_column_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int notification_media_narrow_margin = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int notification_right_icon_size = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int notification_right_side_padding_top = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int notification_small_icon_background_padding = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_small_icon_size_as_large = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_subtext_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_top_pad = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_top_pad_large_text = 2131165203;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000b
			public const int PhoneNumberText = 2131361803;
			
			// aapt resource value: 0x7f0a000e
			public const int TorchOn = 2131361806;
			
			// aapt resource value: 0x7f0a000c
			public const int TranslateButton = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int TranslatedPhoneWord = 2131361805;
			
			// aapt resource value: 0x7f0a000f
			public const int action_container = 2131361807;
			
			// aapt resource value: 0x7f0a001b
			public const int action_divider = 2131361819;
			
			// aapt resource value: 0x7f0a0010
			public const int action_image = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int action_text = 2131361809;
			
			// aapt resource value: 0x7f0a001c
			public const int actions = 2131361820;
			
			// aapt resource value: 0x7f0a0005
			public const int async = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int blocking = 2131361798;
			
			// aapt resource value: 0x7f0a001a
			public const int chronometer = 2131361818;
			
			// aapt resource value: 0x7f0a0007
			public const int forever = 2131361799;
			
			// aapt resource value: 0x7f0a0013
			public const int icon = 2131361811;
			
			// aapt resource value: 0x7f0a001d
			public const int icon_group = 2131361821;
			
			// aapt resource value: 0x7f0a0016
			public const int info = 2131361814;
			
			// aapt resource value: 0x7f0a0008
			public const int italic = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0009
			public const int normal = 2131361801;
			
			// aapt resource value: 0x7f0a0018
			public const int notification_background = 2131361816;
			
			// aapt resource value: 0x7f0a0014
			public const int notification_main_column = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_main_column_container = 2131361810;
			
			// aapt resource value: 0x7f0a0017
			public const int right_icon = 2131361815;
			
			// aapt resource value: 0x7f0a0015
			public const int right_side = 2131361813;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a000a
			public const int textView1 = 2131361802;
			
			// aapt resource value: 0x7f0a0019
			public const int time = 2131361817;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_template_custom_big = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_icon_group = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_part_chronometer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_part_time = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int xamarin_essentials_fileprovider_file_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
